#!/bin/bash
#
# Check a LaTeX file for spelling errors and common typos
#

#
# Boxed output
#

function boxes()
{
  local s="$*"
  tput setaf 7
  echo " -${s//?/-}-
| ${s//?/ } |
| $(tput setaf 3)$s$(tput setaf 7) |
| ${s//?/ } |
 -${s//?/-}-"
  tput sgr 0
}
      
#
# Colors for grep
#

export GREP_COLORS='ms=03;33'
export PCREGREP_COLOR='03;33'
                                               
#
# Parse command line
#

USE="$(basename "$0") [-h] [-n] [-d en_GB-ise] [FILE] -- spell-check a LaTeX file and check for common typos"
DICT=en_GB-ise

while getopts 'h:d:n' option; do
    case "$option" in
        h) echo "$USE"
           exit 1
           ;;
        d) DICT="$OPTARG"
           ;;
        n) NO_SPELL="N"
           ;;
        \?) echo "$USE"
           exit 0
           ;;
    esac
done

shift "$((OPTIND - 1))"
TEX=$1

if [ -z "$TEX" ]; then
    echo "$USE"
    exit 0
fi

if ! [ -e "$TEX" ]; then
    echo "Error - cannot access $TEX. No such file."
    exit 0
fi

#
# Check spelling with aspell - see http://aspell.net/0.50-doc/man-html/4_Customizing.html
#

if [ -z "$NO_SPELL" ]; then

    boxes "Spelling with $DICT dictionary"

    aspell \
    --home-dir "$(dirname $(readlink -f $0))" \
    --sug-mode normal \
    --mode=tex \
    --master="$DICT" \
    --dont-tex-check-comments\
    check "$TEX" # Finally check!

fi

# Show changes

wdiff -w $'\033[03;2m' -x $' =>\033[0m' -y $'\033[03;33m' -z $'\033[0m' -3 "$TEX".bak "$TEX" | sed -e 's/==//g' | cat -s

#
# Check for missing bibliography items
#

BASE=$(echo "$TEX" | cut -f 1 -d '.')
BIBLOG=$BASE.blg

boxes "Warnings from $BIBLOG"

if ! [ -e "$BIBLOG" ] || [ -z "$BIBLOG" ]; then
    echo "Error - cannot access $BIBLOG. No such file."
else
    grep --color 'Warning' "$BIBLOG"
fi

#
# Missing space in new sentence
#

boxes "Missing space in new sentence"
grep -TEni --color=always '\.[a-z]' "$TEX" | grep -Ev '\.pdf'  # Ignore inclusion of e.g. pdf figures

#
# Missing space before or after bracket
#

boxes "Missing spaces around brackets"
grep -TEni --color '\)[a-z]' "$TEX" 
grep -TEni --color '[a-z]\(' "$TEX"

#
# Missing capital in new sentence
#

boxes "Missing capital in new sentence"
pcregrep -Mn --color=always '\w\.\s+[a-z]' "$TEX" | sed -E 's/(^\w+:)/  \1\t/g'

#
# Repeated words
#

boxes "Repeated words"
pcregrep -Mn --color '\b(\w+)\s+\1\b' "$TEX" | sed -E 's/(^\w+:)/  \1\t/g'

#
# Footnote spacing
#

boxes "Footnote spacing"
grep -TEni --color '[^\.]\\footnote{' "$TEX"

#
# Check \cite spacing
#

boxes "\\cite spacing"
if grep -Eiq '\s+\\cite{' "$TEX" && grep -Eiq '[a-z]\\cite{' "$TEX"; then
    grep -TEni -m 1 --color '\s+\\cite{' "$TEX"
    grep -TEni -m 1 --color '[a-z]\\cite{' "$TEX"
fi

#
# a versus an
#

boxes "a versus an"
grep -TEni --color '\ba\s+[aeiou]' "$TEX"
grep -TEni --color=always '\ban\s+[a-z]' "$TEX" | grep -Ev 'an\s+[aeiou]'
