#!/bin/bash
#
# Check a LaTeX file for spelling errors and common typos

HOME=$(dirname "$(readlink -f "$0")")
DICT=en_GB-ise
EMPH='\033[1;31m'
RESET='\033[0m'

function header()
{
local line="$*"
  echo -e "\n${EMPH}${line}${RESET}"
  local length=${#line}
  echo -e "${EMPH}$(printf '%*s' "$length" '' | tr ' ' '=')${RESET}\n"
}

function prettify
{
  sed -E 's/^([0-9]):/L\1:   /g' | sed -E 's/^([0-9]{2}):/L\1:  /g' | sed -E 's/^([0-9]{3}):/L\1: /g' | sed -E 's/^L[0-9]+:/\x1b[1m\x1b[31m&\x1b[0m/g'
}
     
function spell_check()
{
    # check spelling with aspell - see http://aspell.net/0.50-doc/man-html/4_Customizing.html

    dictionary_name=$1
    home_dir=$2
    tex_file_name=$3

    aspell\
    --sug-mode normal\
    --mode=tex\
    --master="$dictionary_name"\
    --dont-tex-check-comments\
    --personal="$home_dir/allowed_words.txt"\
    --per-conf="$home_dir/commands.txt"\
    check "$tex_file_name"
    
    # show changes

    if [ -f "$tex_file_name".bak ]; then
      header "Spell check fixes"
      wdiff -w $'\033[1;31m' -x $' =>\033[0m' -y $'\e[1;32m' -z $'\033[0m' -3 "$tex_file_name".bak "$tex_file_name" | sed -e 's/==//g' | sed -e 's/^ //g' | cat -s
    fi
}

function space_new_sentence() 
{
  # find missing spaces before new sentence
  tex_file_name=$1
  pcregrep -Mn --color=always '\.\w' "$tex_file_name"
}

function space_bracket()
{
  # find problematic spaces around brackets
  tex_file_name=$1
  pcregrep -Mn --color=always '\)\w' "$tex_file_name" 
  pcregrep -Mn --color=always '\w\(' "$tex_file_name"
  pcregrep -Mn --color=always '\s+\)' "$tex_file_name" 
  pcregrep -Mn --color=always '\(\s+' "$tex_file_name"
}

function capital_new_sentence()
{
  # find sentences that do not start with capital
  tex_file_name=$1
  pcregrep -Mn --color=always '\w\.\s+[a-z]' "$tex_file_name" 
}

function space_footnote()
{
  # check that footnote does not have space before it
  tex_file_name=$1
  pcregrep -Mn --color=always '[^\.]\\footnote{' "$tex_file_name"
}

function space_cite()
{
  # check consistent spacing around cite
  tex_file_name=$1
  if pcregrep -Mnq '\s+\\cite{' "$tex_file_name" && pcregrep -Mnq '\w\\cite{' "$tex_file_name"; then
      pcregrep -Mn --color=always '\s+\\cite{' "$tex_file_name"
      pcregrep -Mn --color=always '\w\\cite{' "$tex_file_name"
  fi
}

function space_abbrevation()
{
  # check consistent spacing around cite
  tex_file_name=$1
  pcregrep -Mni --color=always 'Dr.\s+' "$tex_file_name"
  pcregrep -Mni --color=always 'Prof.\s+' "$tex_file_name"
  pcregrep -Mni --color=always 'e.g.\s+' "$tex_file_name"
  pcregrep -Mni --color=always 'i.e.\s+' "$tex_file_name"
}


function repeated_words()
{
  # find repeated words
  tex_file_name=$1
  pcregrep -Mn --color=always '\b(\w+)\s+\1\b' "$tex_file_name"
}

function a_versus_an()
{
  # check for a versus an
  tex_file_name=$1
  pcregrep -Mni --color=always '\ba\s+[aeiou]' "$tex_file_name"
  pcregrep -Mni --color=always '\ban\s+[a-z]' "$tex_file_name" | pcregrep -Miv 'an\s+[aeiou]'
}
                                                   
# parse command line

USE="$(basename "$0") [-h] [-n] [-d en_GB-ise] [FILE] -- spell-check a LaTeX file and check for common typos"

while getopts 'h:d' option; do
    case "$option" in
        h) echo "$USE"
           exit 1
           ;;
        d) DICT="$OPTARG"
           ;;
        \?) echo "$USE"
           exit 0
           ;;
    esac
done

shift "$((OPTIND - 1))"
tex_file_name=$1

if [ -z "$tex_file_name" ]; then
    echo "$USE"
    exit 0
fi

# check file exists

if [ ! -f "$tex_file_name" ]; then
    echo "$tex_file_name: cannot open \`$tex_file_name' (No such file or directory)"
    exit 0
fi

# run checks

spell_check "$DICT" "$HOME" "$tex_file_name"

header "Missing space before new sentence"
space_new_sentence "$tex_file_name" | prettify

header "Missing spaces before or after brackets"
space_bracket "$tex_file_name" | prettify

header "Extra space before footnote command"
space_footnote "$tex_file_name" | prettify

header "Inconsistent space around cite command"
space_cite "$tex_file_name" | prettify

header "Missing capital in new sentence"
capital_new_sentence "$tex_file_name" | prettify

header "Repeated words"
repeated_words "$tex_file_name" | prettify

header "a versus an"
a_versus_an "$tex_file_name" | prettify

header "Extra space around abbreviation"
space_abbrevation "$tex_file_name" | prettify
